steps:
# Pull the latest gcloud image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/cloud-builders/gcloud']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/git', '.']
# Clone a public repo and write its revision to a VERSION file.
- name: 'gcr.io/$PROJECT_ID/git'
  args: ['clone', 'pwd', 'ls']  

  
